const blouseData=[
    {
        id:1,
        img:"/images/b1.png"
    },
    {
        id:2,
        img:"/images/b2.png"
    },
    {
        id:3,
        img:"/images/b3.png"
    },
    {
        id:4,
        img:"/images/b4.png"
    },
    {
        id:5,
        img:"/images/b5.png"
    },
    {
        id:6,
        img:"/images/b1.png"
    },
    {
        id:7,
        img:"/images/b1.png"
    },
    {
        id:8,
        img:"/images/b1.png"
    },
    {
        id:9,
        img:"/images/b1.png"
    },
    {
        id:10,
        img:"/images/b1.png"
    },
    {
        id:11,
        img:"/images/b1.png"
    },
    {
        id:12,
        img:"/images/b1.png"
    },
    {
        id:13,
        img:"/images/b1.png"
    },
    {
        id:14,
        img:"/images/b1.png"
    },
    {
        id:15,
        img:"/images/b1.png"
    },
    {
        id:16,
        img:"/images/b1.png"
    },
    {
        id:17,
        img:"/images/b1.png"
    },
    {
        id:18,
        img:"/images/b2.png"
    },
    {
        id:19,
        img:"/images/b3.png"
    },
    {
        id:20,
        img:"/images/b4.png"
    },
    {
        id:21,
        img:"/images/b5.png"
    },
]
export default blouseData;